begin;
select plan(16);
select ok((select relrowsecurity from pg_class where oid='public.collective_cross_listings'::regclass),'listing table is RLS protected');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='collective_cross_listings'),0,'browser has no listing policies');
select ok(not has_table_privilege('anon','public.collective_cross_listings','SELECT'),'anonymous cannot read partner requests');
select ok(not has_table_privilege('authenticated','public.collective_cross_listings','SELECT'),'signed in callers cannot bypass owner reads');
select ok(not has_table_privilege('authenticated','public.collective_cross_listings','INSERT'),'signed in callers cannot bypass consent');
select ok(not has_table_privilege('authenticated','public.collective_cross_listings','UPDATE'),'signed in callers cannot accept their own request');
select ok(not has_table_privilege('authenticated','public.collective_cross_listings','DELETE'),'signed in callers cannot remove another owner listing');
select ok(has_table_privilege('service_role','public.collective_cross_listings','INSERT'),'owner-gated service can request');
select ok(exists(select 1 from pg_constraint where conrelid='public.collective_cross_listings'::regclass and confrelid='public.journey_plans'::regclass and contype='f' and confdeltype='c'),'Journey deletion cascades listing');
select ok(exists(select 1 from pg_constraint where conrelid='public.collective_cross_listings'::regclass and confrelid='public.circles'::regclass and contype='f' and confdeltype='c'),'Circle deletion cascades listing');
select ok(exists(select 1 from pg_index where indrelid='public.collective_cross_listings'::regclass and indisunique and indpred is not null),'one live listing per subject and destination');
select is((select count(*)::integer from information_schema.columns where table_schema='public' and table_name='collective_cross_listings' and column_name in ('kind','subject_id') and is_generated='ALWAYS'),2,'subject identifiers are generated from real foreign keys');
select ok(not has_function_privilege('anon','public.read_collective_cross_listings(text,uuid,boolean)','EXECUTE'),'anonymous cannot bypass current consent snapshot');
select ok(not has_function_privilege('authenticated','public.read_collective_cross_listings(text,uuid,boolean)','EXECUTE'),'authenticated callers cannot bypass owner boundary');
select ok(has_function_privilege('service_role','public.read_collective_cross_listings(text,uuid,boolean)','EXECUTE'),'service reader can resolve authorized subject snapshot');
select is((select count(*)::integer from pg_trigger where not tgisinternal and tgname in ('collective_listing_owner_transfer','collective_listing_journey_transfer','collective_listing_circle_transfer')),3,'canonical owner/source transfers permanently invalidate consent');
select * from finish();
rollback;
