import type { ElementType } from 'react'
import {
  Radio,
  Home,
  Users,
  CalendarDays,
  Globe,
  Shield,
  MessageSquare,
  Megaphone,
  UserPlus,
  Zap,
  Gem,
  Store,
  Briefcase,
  FileText,
  Sparkles,
  BookOpen,
  Send,
  Contact,
  ContactRound,
  LayoutDashboard,
  LayoutGrid,
  Building2,
  Activity,
  Bot,
  Compass,
  Route,
  QrCode,
  Library,
  LifeBuoy,
  NotebookPen,
  Network,
  Coins,
  Banknote,
  Settings,
  Gamepad2,
  SlidersHorizontal,
  TrendingUp,
  Flag,
  CreditCard,
  BellRing,
  HelpCircle,
  User,
} from 'lucide-react'

// Maps each NAV_AREAS key (lib/nav-areas.ts — the framework-free source of truth)
// to its lucide icon. Used by the single left rail (app-shell.tsx) — desktop and
// the mobile drawer — so every surface stays in lockstep. To give a new area an
// icon, add its key here.
export const AREA_ICONS: Record<string, ElementType> = {
  feed: Home,
  lead: Flag,
  circles: Users,
  channels: Radio,
  events: CalendarDays,
  market: Store,
  practices: Sparkles,
  journeys: Route,
  programs: BookOpen,
  library: Library,
  broadcast: Megaphone,
  messages: MessageSquare,
  friends: UserPlus,
  partners: Store,
  people: Globe,
  codes: QrCode,
  crew: Zap,
  quest: Compass,
  quests: Compass,
  store: Store,
  vault: Gem,
  messageBoards: MessageSquare,
  website: Globe,
  'hook-network': Network,
  earnings: Coins,
  status: LayoutDashboard,
  financials: Banknote,
  settings: Settings,
  'admin-community': Users,
  'admin-home': LayoutDashboard,
  'admin-programs': Gamepad2,
  'admin-operations': SlidersHorizontal,
  'admin-growth': TrendingUp,
  'admin-support': LifeBuoy,
  'admin-structure': Building2,
  'admin-insights': Activity,
  'admin-vera': Bot,
  'admin-vera-ai': Bot,
  'admin-platform': Shield,
  'admin-qr': QrCode,
  'admin-spaces': LayoutGrid,
  crm: Contact,
  connections: ContactRound,
  journal: NotebookPen,
  marketing: Briefcase,
  outreach: Send,
  growth: Sparkles,
  pages: FileText,
}

// Fallback for any key without an explicit icon above.
export const FALLBACK_AREA_ICON: ElementType = Globe

// Lucide icons by their PascalCase NAME — the vocabulary a CUSTOM DB menu row can
// store in `icon` (the code defaults store a NAV_AREAS KEY instead, resolved via
// AREA_ICONS above). Seeded from the icons this module already imports, so a custom
// row can pick any of them with ZERO extra bundle cost; an unknown name falls back.
// To widen the vocabulary, import another lucide icon above and add it here.
const LUCIDE_BY_NAME: Record<string, ElementType> = {
  Radio,
  Home,
  Users,
  CalendarDays,
  Globe,
  Shield,
  MessageSquare,
  Megaphone,
  UserPlus,
  Zap,
  Gem,
  Store,
  Briefcase,
  FileText,
  Sparkles,
  BookOpen,
  Send,
  Contact,
  ContactRound,
  LayoutDashboard,
  LayoutGrid,
  Building2,
  Activity,
  Bot,
  Compass,
  Route,
  QrCode,
  Library,
  LifeBuoy,
  NotebookPen,
  Network,
  Coins,
  Banknote,
  Settings,
  Gamepad2,
  SlidersHorizontal,
  TrendingUp,
  Flag,
  CreditCard,
  BellRing,
  HelpCircle,
  User,
}

// Resolve a menu item's stored `icon` string to an icon component, for the DB-backed
// rail (lib/menus). The defaults store a NAV_AREAS KEY (e.g. 'feed'), so try AREA_ICONS
// first; a custom DB row may store a lucide NAME (e.g. 'Sparkles'), so try LUCIDE_BY_NAME
// next; anything unknown (or absent) gets the safe fallback so a row never renders icon-less.
export function railIconFor(icon: string | undefined): ElementType {
  if (!icon) return FALLBACK_AREA_ICON
  return AREA_ICONS[icon] ?? LUCIDE_BY_NAME[icon] ?? FALLBACK_AREA_ICON
}
