// Phase C (ADR-088 §6) — lean Room AI: semantic search over a room's message
// history. Reuses the gte-small `embed` edge function + the AI kill-switch/budget
// ledger. Embeddings are generated by a cron backfill (cheap, no trigger plumbing);
// search degrades to a deterministic substring scan when AI is off or over budget.
// Server-only (admin client). room_messages.embedding isn't in the generated types
// yet → untyped cast (repo convention).

import type { SupabaseClient } from '@supabase/supabase-js'
import { createAdminClient } from '@/lib/supabase/admin'
import { embedText } from '@/lib/ai/embed'
import { aiAvailable, featureOverBudget, recordAiUsage } from '@/lib/ai/usage'
import { escapeLike } from '@/lib/search-sanitize'

const FEATURE = 'room-search'

export interface RoomSearchHit {
  id: string
  author_id: string
  body: string
  created_at: string
  /** Cosine similarity (semantic) or 0 (substring fallback). */
  similarity: number
}

/** pgvector wants a bracketed literal for a vector parameter over PostgREST. */
function toVectorLiteral(v: number[]): string {
  return `[${v.join(',')}]`
}

function db(): SupabaseClient {
  return createAdminClient()
}

/** Deterministic, zero-cost fallback (and the path for un-embedded rooms). */
async function substringSearch(roomId: string, q: string, limit: number): Promise<RoomSearchHit[]> {
  const { data } = await db()
    .from('room_messages')
    .select('id, author_id, body, created_at')
    .eq('room_id', roomId)
    .ilike('body', `%${escapeLike(q)}%`)
    .order('created_at', { ascending: false })
    .limit(limit)
  return ((data ?? []) as Omit<RoomSearchHit, 'similarity'>[]).map((m) => ({ ...m, similarity: 0 }))
}

/**
 * Search one room's history. Semantic when AI is on + in budget; otherwise a
 * substring scan. Caller passes a roomId they can see (the RPC re-checks via
 * am_room_member / channel visibility). `mode` tells the UI which path ran.
 */
export async function searchRoom(
  roomId: string,
  query: string,
  profileId: string | null,
  limit = 12,
): Promise<{ hits: RoomSearchHit[]; mode: 'semantic' | 'text' }> {
  const q = query.trim().slice(0, 300)
  if (!q) return { hits: [], mode: 'text' }

  if (!(await aiAvailable()) || (await featureOverBudget(FEATURE))) {
    return { hits: await substringSearch(roomId, q, limit), mode: 'text' }
  }

  try {
    const embedding = await embedText(q)
    const { data, error } = await db().rpc('match_room_messages', {
      _room_id: roomId,
      query_embedding: toVectorLiteral(embedding),
      match_count: limit,
    })
    if (error) throw new Error(error.message)
    // Embeddings are free (edge fn); log a zero-cost row for visibility/auditing.
    void recordAiUsage({ feature: FEATURE, model: 'gte-small', usage: { inputTokens: 0, outputTokens: 0 }, costUsd: 0, profileId })
    const hits = (data ?? []) as RoomSearchHit[]
    // No semantic hits (e.g. nothing embedded yet) → fall back so search still works.
    return hits.length > 0 ? { hits, mode: 'semantic' } : { hits: await substringSearch(roomId, q, limit), mode: 'text' }
  } catch {
    return { hits: await substringSearch(roomId, q, limit), mode: 'text' }
  }
}

/**
 * Embed up to `batch` room messages that don't have an embedding yet (newest
 * first, so search is freshest). Driven by the cron. Best-effort per message.
 * Returns how many were embedded.
 */
export async function embedRoomMessageBacklog(batch = 100): Promise<{ embedded: number; remaining: number }> {
  const client = db()
  const { data, count } = await client
    .from('room_messages')
    .select('id, body', { count: 'exact' })
    .is('embedding', null)
    .not('body', 'is', null)
    .order('created_at', { ascending: false })
    .limit(batch)

  const rows = (data ?? []) as { id: string; body: string | null }[]
  let embedded = 0
  for (const m of rows) {
    const text = (m.body ?? '').trim()
    if (!text) {
      // Nothing to embed — store a zero vector so it isn't rescanned forever.
      await client.from('room_messages').update({ embedding: `[${new Array(384).fill(0).join(',')}]` }).eq('id', m.id)
      continue
    }
    try {
      const v = await embedText(text.slice(0, 2000))
      await client.from('room_messages').update({ embedding: toVectorLiteral(v) }).eq('id', m.id)
      embedded++
    } catch {
      /* skip; the next run retries */
    }
  }
  return { embedded, remaining: Math.max(0, (count ?? 0) - embedded) }
}
