-- =====================================================================
-- Demo seed — VERTICAL 3: National network — RETIRED (no-op)
-- =====================================================================
-- This migration formerly seeded ~16 demo Circles + ~90 demo members across
-- Austin, Boulder, Asheville, Brooklyn, and Bend, with their memberships,
-- role-voiced posts, and upcoming events (all is_demo = true).
--
-- The demo program is retired: demo_mode defaults off and the national-metro
-- geography is purged in 20260817000000_retire_demo_seed.sql. The body is
-- intentionally emptied so a fresh database never recreates the national demo
-- set; the file is kept as a no-op to preserve migration ordering, and the data
-- it created on existing environments is removed by the retire migration.
--
-- See docs/DECISIONS.md ADR-400.
-- =====================================================================
SELECT 1;
