-- =============================================================================
-- Movement timer: promote the binary `uses_timer` to a `timer_kind` enum
-- (none | mindless | movement) + an optional `movement_config` jsonb on practices
-- (WEBSITE-CHANGES-PLAN §4 C.8 / D6).
--
-- WHY: a practice now routes to one of two timers, not just "timer yes/no". The
-- launcher / Journey step / practice page read `timer_kind` to open the Mindless
-- sit (useMindless) vs the Movement timer (useMovement); `duration_min` seeds
-- both, and `movement_config` carries the Movement mode (+ tuning) the author set.
--
-- BACK-COMPAT: `uses_timer` is KEPT and stays the source of truth for "is this a
-- timed practice at all" (any non-'none' kind). A generated column derives it from
-- timer_kind so old reads (lib/practices, the timer-proof in completeSession, the
-- practices_ranked view) keep working untouched and the two can never drift.
--   - Pre-existing uses_timer = true  -> 'mindless' (the only timer there was)
--   - Pre-existing uses_timer = false -> 'none'
--
-- NOTE: regenerate lib/database.types.ts after apply (the integrator's step). Until
-- then lib/practices.ts reaches timer_kind / movement_config through its untyped
-- admin handle (ADR-246 untyped casts).
-- =============================================================================

-- 1. The enum.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'practice_timer_kind') then
    create type public.practice_timer_kind as enum ('none', 'mindless', 'movement');
  end if;
end$$;

-- 2. The new columns. timer_kind is seeded from the existing uses_timer flag; the
--    Movement config is an optional jsonb ({ mode, walkMinutes, yogaKind, ... }).
alter table public.practices
  add column if not exists timer_kind public.practice_timer_kind;

alter table public.practices
  add column if not exists movement_config jsonb;

-- Seed timer_kind from the binary flag for every existing row (idempotent: only
-- fills rows that haven't been set yet).
update public.practices
  set timer_kind = case when uses_timer then 'mindless'::public.practice_timer_kind
                        else 'none'::public.practice_timer_kind end
  where timer_kind is null;

-- New rows default to 'mindless' (most library practices are sits/breathwork),
-- matching the prior `uses_timer default true`.
alter table public.practices
  alter column timer_kind set default 'mindless'::public.practice_timer_kind,
  alter column timer_kind set not null;

comment on column public.practices.timer_kind is
  'Which timer a practice routes to: none (one-tap Log it) | mindless (the On Air sit/breathe) | movement (the Movement timer). Supersedes the binary uses_timer, which is now derived from this. duration_min seeds the timer.';
comment on column public.practices.movement_config is
  'Movement timer config when timer_kind = movement: { mode: walk|yoga|play|workout, plus the mode tuning (walkMinutes, walkIntervalMin, yogaKind, workoutKind, workSec, restSec, rounds) }. Mirrors lib/movement.ts MovementConfig. Null otherwise.';

-- 3. Keep uses_timer as a DERIVED mirror so every existing reader (the timer-proof
--    in completeSession, the practices_ranked view, lib/practices) is unchanged and
--    the flag can never drift from the kind. Drop the old default first, then make
--    it a generated stored column = (timer_kind <> 'none').
alter table public.practices
  alter column uses_timer drop default;

-- A column can only become generated when it has no plain values to conflict with;
-- since uses_timer already exists with data, recreate it as generated by swapping
-- through a temp column. (Postgres has no ALTER ... SET GENERATED for an existing
-- plain column.)
alter table public.practices
  add column if not exists uses_timer_derived boolean
    generated always as (timer_kind <> 'none'::public.practice_timer_kind) stored;

-- Move readers onto the generated value: drop the old plain column and rename the
-- generated one into its place. practices_ranked is recreated below to pick it up.
-- (If practices_ranked currently selects uses_timer, it must be dropped first; the
-- create-or-replace below restores it identically with the generated column.)
drop view if exists public.practices_ranked;

alter table public.practices drop column uses_timer;
alter table public.practices rename column uses_timer_derived to uses_timer;

comment on column public.practices.uses_timer is
  'DERIVED (generated) from timer_kind: true when timer_kind <> none. Kept for back-compat (Journey-step action, the On Air timer-proof, practices_ranked). Authoritative source is timer_kind.';

-- 4. Recreate practices_ranked exactly as before (uses_timer now reads the generated
--    column transparently; the two new practice columns are NOT exposed on the view,
--    which the library does not need — the editor + routing read them from the table).
create or replace view public.practices_ranked as
  select
    p.id,
    p.title,
    p.description,
    p.created_by,
    p.is_public,
    p.created_at,
    p.is_demo,
    p.category,
    p.icon,
    p.summary,
    p.header_image,
    p.body,
    p.cadence,
    p.reward_zaps,
    p.reward_note,
    p.domain_id,
    p.status,
    p.reviewed_by,
    p.reviewed_at,
    p.subcategory_id,
    p.embedding,
    p.is_template,
    p.featured_at,
    p.weight_class,
    coalesce(a.adopters, 0::bigint) as adopters,
    coalesce(l.logs_30d, 0::bigint) as logs_30d,
    coalesce(l.logs_total, 0::bigint) as logs_total,
    coalesce(l.logs_30d, 0::bigint) * 3 + coalesce(a.adopters, 0::bigint) * 2 + coalesce(l.logs_total, 0::bigint) as score,
    p.focus_details,
    p.duration_min,
    p.uses_timer
  from practices p
    left join (
      select member_practices.practice_id, count(*) as adopters
      from member_practices
      where member_practices.active = true
      group by member_practices.practice_id
    ) a on a.practice_id = p.id
    left join (
      select practice_logs.practice_id,
        count(*) filter (where practice_logs.logged_for >= (current_date - 30)) as logs_30d,
        count(*) as logs_total
      from practice_logs
      group by practice_logs.practice_id
    ) l on l.practice_id = p.id;
