-- =============================================================================
-- Support & bug-reporting system (ADR-159, docs/SUPPORT-SYSTEM.md)
--
-- An integrated, cataloged communication system: members file bug reports / support
-- requests (with page + activity context and a screenshot) from anywhere on the
-- site or from the Vera chat box; they track their ticket history; staff triage and
-- reply from an admin console wired to the member's profile/CRM; and Vera can read a
-- member's ticket history in conversation.
--
-- Two tables: a ticket + its threaded messages (member replies, staff replies, and
-- staff-only internal notes). Member reads are governed by RLS; staff reads/writes go
-- through the service-role admin client behind app-code authz (repo convention).
-- Screenshots live in a PRIVATE `support` storage bucket, served via short-lived
-- signed URLs from the server (never a public URL — reports can contain sensitive
-- on-screen data).
-- =============================================================================

-- A human-friendly, monotonic ticket reference (#1000, #1001, …) on top of the uuid.
create table if not exists public.support_tickets (
  id              uuid primary key default gen_random_uuid(),
  ref             bigint generated by default as identity (start with 1000),
  profile_id      uuid not null references public.profiles(id) on delete cascade,
  type            text not null default 'bug'    check (type in ('bug','question','feedback','idea')),
  subject         text not null,
  status          text not null default 'open'   check (status in ('open','in_progress','waiting','resolved','closed')),
  priority        text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  page_url        text,
  -- Captured page + activity data: route, viewport, user agent, referrer, app
  -- version, timestamp, and any breadcrumb the client gathers.
  context         jsonb not null default '{}'::jsonb,
  -- Storage path in the private `support` bucket (not a public URL).
  screenshot_path text,
  assigned_to     uuid references public.profiles(id) on delete set null,
  resolved_at     timestamptz,
  last_activity_at timestamptz not null default now(),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists support_tickets_ref_idx       on public.support_tickets (ref);
create index if not exists support_tickets_profile_idx          on public.support_tickets (profile_id, created_at desc);
create index if not exists support_tickets_status_idx           on public.support_tickets (status, last_activity_at desc);
create index if not exists support_tickets_assignee_idx         on public.support_tickets (assigned_to) where assigned_to is not null;
create index if not exists support_tickets_type_idx             on public.support_tickets (type);

create table if not exists public.support_ticket_messages (
  id          uuid primary key default gen_random_uuid(),
  ticket_id   uuid not null references public.support_tickets(id) on delete cascade,
  -- Null for system/vera authored lines; a profile id for member/staff.
  author_id   uuid references public.profiles(id) on delete set null,
  author_kind text not null default 'member' check (author_kind in ('member','staff','vera','system')),
  body        text not null,
  -- Staff-only note (never shown to the member); the member thread filters these out.
  is_internal boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists support_ticket_messages_ticket_idx on public.support_ticket_messages (ticket_id, created_at);

-- ── RLS — member self-service; staff go through the service-role admin client ──
alter table public.support_tickets         enable row level security;
alter table public.support_ticket_messages enable row level security;

-- A member sees and files their own tickets.
drop policy if exists support_tickets_select on public.support_tickets;
create policy support_tickets_select on public.support_tickets
  for select using (profile_id = get_my_profile_id());

drop policy if exists support_tickets_insert on public.support_tickets;
create policy support_tickets_insert on public.support_tickets
  for insert with check (profile_id = get_my_profile_id());

-- Messages: a member sees the NON-internal thread of their own tickets, and can add
-- their own (non-internal) replies. Staff replies/notes are written by the admin client.
drop policy if exists support_ticket_messages_select on public.support_ticket_messages;
create policy support_ticket_messages_select on public.support_ticket_messages
  for select using (
    is_internal = false
    and exists (
      select 1 from public.support_tickets t
      where t.id = ticket_id and t.profile_id = get_my_profile_id()
    )
  );

drop policy if exists support_ticket_messages_insert on public.support_ticket_messages;
create policy support_ticket_messages_insert on public.support_ticket_messages
  for insert with check (
    is_internal = false
    and author_id = get_my_profile_id()
    and exists (
      select 1 from public.support_tickets t
      where t.id = ticket_id and t.profile_id = get_my_profile_id()
    )
  );

-- ── Private storage bucket for screenshots (signed-URL access only) ──
insert into storage.buckets (id, name, public)
values ('support', 'support', false)
on conflict (id) do nothing;
