-- =============================================================================
-- Event matching engine — embeddings + AI-blurb cache (docs/EVENTS-SYSTEM.md §3)
--
-- The semantic backbone for "For You": a 384-d gte-small embedding per event
-- (title + description + category + energy_tag), generated by a cheap cron
-- backfill (no insert trigger), and a small per-(profile,event,day) cache for the
-- AI "why you'd vibe" blurb so we never re-spend Haiku on the same pairing twice
-- in a day.
--
-- Embedding dim is 384 (gte-small via the `embed` edge function — NOT 1536); the
-- hnsw vector_cosine_ops index mirrors profiles/groups (initial_schema.sql) and
-- room_messages (20260606120000).
--
-- RLS: both tables are server/service-role only — RLS ON, NO client policy — like
-- every other embedding-backed / AI-derived table. Clients never read these
-- directly; the matching engine runs on the admin client.
-- =============================================================================

create extension if not exists vector;

-- ── event_embeddings ─────────────────────────────────────────────────────────
create table if not exists public.event_embeddings (
  event_id   uuid        primary key references public.events (id) on delete cascade,
  embedding  vector(384),
  updated_at timestamptz not null default now()
);

create index if not exists event_embeddings_embedding_idx
  on public.event_embeddings using hnsw (embedding vector_cosine_ops)
  where embedding is not null;

comment on table public.event_embeddings is
  '384-d gte-small embedding per event (title+description+category+energy_tag) powering hybrid "For You" matching. Server/service-role only; refreshed by the embed-events cron.';

alter table public.event_embeddings enable row level security;
-- No SELECT/INSERT/UPDATE/DELETE policy on purpose: deny all client access. Only
-- the service role (which bypasses RLS) reads/writes, exactly like other
-- embedding-backed tables.

-- ── event_blurb_cache ────────────────────────────────────────────────────────
-- One warm AI sentence per (viewer, event, UTC day). day_key keeps it cheap: a
-- new row per day, old rows harmless. NULL blurb is a valid cached "no usable
-- overlap / AI returned nothing" result so we don't retry it the same day.
create table if not exists public.event_blurb_cache (
  profile_id uuid        not null references public.profiles (id) on delete cascade,
  event_id   uuid        not null references public.events   (id) on delete cascade,
  day_key    date        not null,
  blurb      text,
  created_at timestamptz not null default now(),
  primary key (profile_id, event_id, day_key)
);

comment on table public.event_blurb_cache is
  'Per-(viewer,event,UTC-day) cache of the AI "why you''d vibe" blurb (Haiku). Read-only feature; service-role only. NULL blurb is a valid cached "nothing to say" result.';

alter table public.event_blurb_cache enable row level security;
-- Deny all client access (service-role only), same as event_embeddings.
