-- Conversations spine (ADR-8xx): the unified, channel-agnostic bedrock for ALL in-house Frequency
-- communication. A conversation is a threaded, stateful, assignable exchange with a member or a CRM
-- contact, on any channel. Support tickets, CRM outreach, leader-to-member notes, and inbound replies
-- all become conversations, so there is ONE inbox, ONE history, ONE system of record.
--
-- This migration is ADDITIVE and behind application feature flags: it creates the new tables and links
-- to support_tickets (support_ticket_id) but does NOT rename or alter the live support flow. Folding
-- support_tickets INTO conversations (rename + compatibility views) is a deliberate later step.
--
-- RLS mirrors public.support_tickets: MEMBERS are governed by policies keyed on get_my_profile_id();
-- staff/agents, CRM outreach, broadcast fan-out, and the inbound reply-address router all go through the
-- service-role admin client, which bypasses RLS (same pattern lib/support/store.ts already uses).
--
-- The per-conversation reply address is HMAC-DERIVED from `ref` (lib/comms/reply-address.ts) — no token
-- column is stored: reply+<ref>-<hmac>@<reply-domain> is unforgeable + non-enumerable without a lookup.

-- ── conversations ────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.conversations (
  id                  uuid primary key default gen_random_uuid(),
  ref                 bigint generated by default as identity (start with 1000),

  kind                text not null default 'crm'
                        check (kind in ('support','crm','leader','broadcast','dm','announcement','system')),
  subject             text not null,
  status              text not null default 'open'
                        check (status in ('open','in_progress','waiting','snoozed','resolved','closed')),
  priority            text not null default 'normal'
                        check (priority in ('low','normal','high','urgent')),
  channel             text not null default 'email'
                        check (channel in ('email','sms','in_app','whatsapp','call','note','system')),

  -- COUNTERPARTY (the person on the other side), polymorphic — same vocab as contact_interactions.
  subject_kind        text not null default 'contact'
                        check (subject_kind in ('profile','contact','network_contact')),
  subject_id          uuid,
  member_profile_id   uuid references public.profiles(id) on delete set null,
  contact_id          uuid references public.contacts(id) on delete set null,
  external_email      text,  -- lowercased counterpart address; the anti-spoof anchor on inbound

  -- HOUSE SIDE
  owner_profile_id    uuid references public.profiles(id) on delete set null,  -- the sender-trail owner (leader/operator)
  assigned_to         uuid references public.profiles(id) on delete set null,  -- current agent
  space_id            uuid references public.spaces(id) on delete cascade,     -- NULL = platform-global
  support_ticket_id   uuid references public.support_tickets(id) on delete set null, -- link when kind='support'

  provider_thread_id  text,          -- root Message-ID / provider thread id for outbound threading
  context             jsonb not null default '{}'::jsonb,  -- page/activity capture (support)
  metadata            jsonb not null default '{}'::jsonb,  -- broadcast_id, source, tags, per-channel detail
  ai                  jsonb not null default '{}'::jsonb,  -- Vera seam: {draft, triage, summary, sentiment}

  first_response_at   timestamptz,
  resolved_at         timestamptz,
  sla_due_at          timestamptz,
  snoozed_until       timestamptz,
  last_activity_at    timestamptz not null default now(),
  last_inbound_at     timestamptz,
  last_outbound_at    timestamptz,

  created_by          uuid references public.profiles(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint conversations_counterparty_present
    check (member_profile_id is not null or contact_id is not null or subject_id is not null)
);

create unique index if not exists conversations_ref_idx       on public.conversations (ref);
create index if not exists conversations_member_idx           on public.conversations (member_profile_id, last_activity_at desc);
create index if not exists conversations_contact_idx          on public.conversations (contact_id, last_activity_at desc);
create index if not exists conversations_status_idx           on public.conversations (status, last_activity_at desc);
create index if not exists conversations_assignee_idx         on public.conversations (assigned_to) where assigned_to is not null;
create index if not exists conversations_space_idx            on public.conversations (space_id, last_activity_at desc) where space_id is not null;
create index if not exists conversations_support_ticket_idx   on public.conversations (support_ticket_id) where support_ticket_id is not null;

-- ── conversation_messages ────────────────────────────────────────────────────────────────────────────
create table if not exists public.conversation_messages (
  id                  uuid primary key default gen_random_uuid(),
  conversation_id     uuid not null references public.conversations(id) on delete cascade,

  author_id           uuid references public.profiles(id) on delete set null,  -- member/staff/leader/vera
  author_contact_id   uuid references public.contacts(id) on delete set null,  -- external sender
  author_kind         text not null default 'contact'
                        check (author_kind in ('member','staff','leader','vera','system','contact')),

  direction           text not null default 'inbound'
                        check (direction in ('inbound','outbound','internal')),
  channel             text not null default 'email'
                        check (channel in ('email','sms','in_app','whatsapp','call','note','system')),

  body                text not null,
  body_html           text,
  is_internal         boolean not null default false,  -- agent-only note; never shown to the member

  external_message_id text,        -- provider Message-ID of THIS message (idempotency + threading)
  in_reply_to         text,        -- parent Message-ID
  references_ids      text[],      -- full RFC References chain

  attachments         jsonb not null default '[]'::jsonb,
  metadata            jsonb not null default '{}'::jsonb,
  delivery_status     text not null default 'sent'
                        check (delivery_status in ('queued','sent','delivered','opened','clicked','bounced','failed','received')),

  occurred_at         timestamptz not null default now(),
  created_at          timestamptz not null default now(),

  constraint conversation_messages_author_present
    check (author_id is not null or author_contact_id is not null or author_kind in ('system','vera'))
);

create index if not exists conversation_messages_conv_idx on public.conversation_messages (conversation_id, created_at);
-- Provider dedupe: replaces the coarse from+subject+minute idempotency bucket in lib/crm/inbox.ts.
create unique index if not exists conversation_messages_extid_uniq
  on public.conversation_messages (external_message_id) where external_message_id is not null;

-- ── conversation_assignments (append-only "trade" audit) ───────────────────────────────────────────────
create table if not exists public.conversation_assignments (
  id               uuid primary key default gen_random_uuid(),
  conversation_id  uuid not null references public.conversations(id) on delete cascade,
  assigned_to      uuid references public.profiles(id) on delete set null,  -- NULL = returned to the queue
  assigned_by      uuid references public.profiles(id) on delete set null,  -- who traded it (NULL = system)
  reason           text,  -- 'manual' | 'round_robin' | 'escalation' | 'reopen'
  created_at       timestamptz not null default now()
);
create index if not exists conversation_assignments_conv_idx on public.conversation_assignments (conversation_id, created_at desc);

-- ── the reply-mode flag on campaigns (the composer's per-send choice) ──────────────────────────────────
alter table public.campaigns
  add column if not exists reply_mode text not null default 'broadcast'
    check (reply_mode in ('broadcast','conversation'));

-- ── RLS ────────────────────────────────────────────────────────────────────────────────────────────────
alter table public.conversations           enable row level security;
alter table public.conversation_messages   enable row level security;
alter table public.conversation_assignments enable row level security;

-- A member sees conversations they are the counterparty of; the assigned agent sees their assignments.
-- Staff, CRM, broadcast, and inbound routing use the service-role client (bypasses RLS), as support does.
drop policy if exists conversations_select_member on public.conversations;
create policy conversations_select_member on public.conversations
  for select using (member_profile_id = get_my_profile_id() or assigned_to = get_my_profile_id());

-- A member may OPEN a support conversation about themselves (mirrors support_tickets_insert). All other
-- creates (CRM/leader/broadcast/inbound) are service-role.
drop policy if exists conversations_insert_member on public.conversations;
create policy conversations_insert_member on public.conversations
  for insert with check (
    kind = 'support'
    and member_profile_id = get_my_profile_id()
    and subject_kind = 'profile'
    and subject_id = get_my_profile_id()
  );

-- A member reads the NON-internal thread of their own conversations; the assigned agent reads the full thread.
drop policy if exists conv_messages_select on public.conversation_messages;
create policy conv_messages_select on public.conversation_messages
  for select using (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_id
        and (
          (c.member_profile_id = get_my_profile_id() and is_internal = false)
          or c.assigned_to = get_my_profile_id()
        )
    )
  );

-- A member posts their own non-internal reply (mirrors support_ticket_messages_insert). Staff replies,
-- notes, inbound-webhook writes, and projections are service-role.
drop policy if exists conv_messages_insert_member on public.conversation_messages;
create policy conv_messages_insert_member on public.conversation_messages
  for insert with check (
    is_internal = false
    and direction = 'inbound'
    and author_id = get_my_profile_id()
    and author_kind = 'member'
    and exists (
      select 1 from public.conversations c
      where c.id = conversation_id and c.member_profile_id = get_my_profile_id()
    )
  );

-- Assignment audit is service-role write; the assigned agent may read their own trail.
drop policy if exists conversation_assignments_select on public.conversation_assignments;
create policy conversation_assignments_select on public.conversation_assignments
  for select using (
    assigned_to = get_my_profile_id() or assigned_by = get_my_profile_id()
  );
