-- Generated by CLI as 20261009003352; reserved ordered slot follows existing applied history.
create table public.space_email_domain_operations (
 id uuid primary key default gen_random_uuid(),
 space_id uuid not null references public.spaces(id) on delete cascade,
 owner_profile_id uuid not null references public.profiles(id),
 domain text not null unique,
 nonce uuid not null default gen_random_uuid(),
 state text not null default 'pending' check(state in ('pending','creating','uncertain','persisting','ready')),
 provider_domain_id text,
 lease_until timestamptz,
 started_at timestamptz,
 created_at timestamptz not null default now()
);
create index space_email_domain_operations_space_idx on public.space_email_domain_operations(space_id);
create index space_email_domain_operations_owner_idx on public.space_email_domain_operations(owner_profile_id);
alter table public.space_email_domain_operations enable row level security;
revoke all on public.space_email_domain_operations from public,anon,authenticated;
grant all on public.space_email_domain_operations to service_role;
-- A retry never repeats create once its predecessor crossed the provider boundary.
create function public.claim_space_email_domain_operation(p_id uuid) returns jsonb
language plpgsql security invoker set search_path='' as $$
declare o public.space_email_domain_operations%rowtype; mode text;
begin
 select * into o from public.space_email_domain_operations where id=p_id for update;
 if not found then raise exception 'Email operation is unavailable'; end if;
 if o.lease_until > now() then return jsonb_build_object('mode','busy'); end if;
 mode := case when o.provider_domain_id is not null then 'persist' when o.state='pending' then 'create' else 'reconcile' end;
 update public.space_email_domain_operations set state=case when mode='create' then 'creating' else state end,
  started_at=coalesce(started_at,now()),lease_until=now()+interval '2 minutes' where id=p_id returning * into o;
 return to_jsonb(o)||jsonb_build_object('mode',mode);
end $$;
revoke all on function public.claim_space_email_domain_operation(uuid) from public,anon,authenticated;
grant execute on function public.claim_space_email_domain_operation(uuid) to service_role;
alter table public.space_email_identities add constraint space_email_identities_id_space_unique unique(id,space_id);
create table public.space_email_identity_defaults (
 space_id uuid not null references public.spaces(id) on delete cascade,
 purpose text not null check(purpose in ('conversation','marketing','operational')),
 identity_id uuid not null,
 primary key(space_id,purpose),
 foreign key(identity_id,space_id) references public.space_email_identities(id,space_id)
);
create index space_email_identity_defaults_identity_idx on public.space_email_identity_defaults(identity_id,space_id);
alter table public.space_email_identity_defaults enable row level security;
revoke all on public.space_email_identity_defaults from public,anon,authenticated;
grant select on public.space_email_identity_defaults to authenticated;
grant all on public.space_email_identity_defaults to service_role;
create policy space_email_identity_defaults_owner_read on public.space_email_identity_defaults for select to authenticated
 using(exists(select 1 from public.spaces s join public.profiles p on p.id=s.owner_profile_id
 where s.id=space_email_identity_defaults.space_id and p.auth_user_id=auth.uid()));
