-- LIVE-795 (ADR-1715): one saved segment per archetype, modelled on 20260607010000_persona_segments.sql.
-- The predicate is the archetype's boolean tag (archetype_<id>), registered in lib/traits/registry.ts from
-- the single archetype registry (lib/audience/archetypes.ts). Archetype names are internal: these segments
-- are an operator tool (the campaign composer lists every saved segment) and never a member surface.
-- Data only, idempotent (on conflict do nothing).

insert into public.segments (slug, name, description, definition, is_system) values
  ('archetype-wired-professional',
   'Archetype · Wired Professional',
   'Members who said they can’t switch off. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_wired_professional"}]}'::jsonb,
   true),
  ('archetype-transplant',
   'Archetype · Transplant',
   'Members who said they’re new around here. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_transplant"}]}'::jsonb,
   true),
  ('archetype-activity-first',
   'Archetype · Activity-First',
   'Members who want something to do, like a run or a game night. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_activity_first"}]}'::jsonb,
   true),
  ('archetype-evidence-first',
   'Archetype · Evidence-First Skeptic',
   'Members who want just a timer, no fluff. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_evidence_first"}]}'::jsonb,
   true),
  ('archetype-mission-patron',
   'Archetype · Mission Patron',
   'Members who want to help keep Frequency free. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_mission_patron"}]}'::jsonb,
   true),
  ('archetype-host-connector',
   'Archetype · Host-Connector',
   'Members who want to host but haven’t yet. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_host_connector"}]}'::jsonb,
   true),
  ('archetype-gathering-host',
   'Archetype · Gathering Host',
   'Members who already run something that is growing. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_gathering_host"}]}'::jsonb,
   true),
  ('archetype-portfolio-teacher',
   'Archetype · Portfolio Teacher',
   'Members who teach at a few studios. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_portfolio_teacher"}]}'::jsonb,
   true),
  ('archetype-second-act',
   'Archetype · Second-Act Practitioner',
   'Members who run their own practice. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_second_act"}]}'::jsonb,
   true),
  ('archetype-studio-keeper',
   'Archetype · Studio Keeper',
   'Members who run a studio or space. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_studio_keeper"}]}'::jsonb,
   true),
  ('archetype-network-steward',
   'Archetype · Network Steward',
   'Members who run several groups or a nonprofit. Internal (ADR-1715).',
   '{"combinator":"all","predicates":[{"type":"tag","key":"archetype_network_steward"}]}'::jsonb,
   true)
on conflict (slug) do nothing;
