-- LIVE-883. Generated by CLI as 20261008202026, ordered after prerequisite migrations.
-- Estimates bound concurrent admission; actual invoices may exceed estimates. Never erase unknown spend.
create table public.ai_budget_reservations (
  id uuid primary key,
  operation_id uuid not null,
  feature text not null,
  model text not null,
  profile_id uuid references public.profiles(id) on delete set null,
  space_id uuid references public.spaces(id) on delete set null,
  created_at timestamptz not null default clock_timestamp(),
  budget_day date not null,
  estimated_usd numeric not null check (estimated_usd > 0 and estimated_usd < 'Infinity'::numeric),
  actual_usd numeric check (actual_usd >= 0 and actual_usd < 'Infinity'::numeric),
  state text not null default 'reserved' check (state in ('reserved', 'uncertain', 'settled')),
  reason text check (reason in ('provider_failed', 'stream_failed', 'settle_failed')),
  settled_at timestamptz
);
alter table public.ai_budget_reservations enable row level security;
revoke all on public.ai_budget_reservations from public, anon, authenticated, service_role;
grant select on public.ai_budget_reservations to service_role;
create index ai_budget_reservations_profile_id_idx on public.ai_budget_reservations (profile_id) where profile_id is not null;
create index ai_budget_reservations_space_id_idx on public.ai_budget_reservations (space_id) where space_id is not null;
create index ai_budget_day_idx on public.ai_budget_reservations (budget_day, state, feature);
alter table public.ai_usage add column reservation_id uuid unique references public.ai_budget_reservations(id);

create function public.ai_reserve_attempt(p_id uuid, p_operation uuid, p_feature text, p_model text, p_estimate numeric,
  p_profile uuid, p_space uuid, p_global_cap numeric, p_feature_cap numeric, p_space_cap numeric)
returns boolean language plpgsql security definer set search_path = '' as $$
declare started timestamptz := clock_timestamp(); d date := (started at time zone 'utc')::date; g numeric; f numeric; s numeric;
begin
  if p_estimate is null or p_estimate <= 0 or p_estimate >= 'Infinity'::numeric
    or p_global_cap is null or p_global_cap <= 0 or p_global_cap > 25
    or p_feature_cap is null or p_feature_cap <= 0 or p_feature_cap > p_global_cap
    or p_space_cap is null or p_space_cap <= 0 or p_space_cap > p_feature_cap
    or p_feature is null or p_feature = '' or p_model is null or p_model = '' then
    raise exception 'Invalid AI reservation';
  end if;
  -- Every admission and settlement takes the same daily transaction lock, including different Spaces.
  perform pg_catalog.pg_advisory_xact_lock(883, d - date '2000-01-01');
  if exists(select 1 from public.ai_budget_reservations where id=p_id) then
    raise exception 'Reservation ID already exists';
  end if;
  if not coalesce((select value from public.platform_flags where key='ai_enabled'), false) then return false; end if;
  select coalesce(sum(cost),0), coalesce(sum(cost) filter(where feature=p_feature),0),
    coalesce(sum(cost) filter(where feature=p_feature and space_id=p_space),0) into g,f,s
  from (
    select coalesce(r.actual_usd,u.cost_usd) as cost, u.feature, u.space_id from public.ai_usage u
      left join public.ai_budget_reservations r on r.id=u.reservation_id
      where u.created_at >= d::timestamp at time zone 'utc' and u.created_at < (d+1)::timestamp at time zone 'utc'
    union all
    select estimated_usd, feature, space_id from public.ai_budget_reservations
      where budget_day=d and state in ('reserved','uncertain')
  ) costs;
  if g+p_estimate > p_global_cap or f+p_estimate > p_feature_cap
    or (p_space is not null and s+p_estimate > p_space_cap) then return false; end if;
  insert into public.ai_budget_reservations(id,operation_id,feature,model,profile_id,space_id,created_at,budget_day,estimated_usd)
    values(p_id,p_operation,p_feature,p_model,p_profile,p_space,started,d,p_estimate);
  return true;
end;
$$;
create function public.ai_settle_attempt(p_id uuid, p_input_tokens integer, p_output_tokens integer, p_actual numeric)
returns boolean language plpgsql security definer set search_path = '' as $$
declare r public.ai_budget_reservations%rowtype;
begin
  if p_actual is null or p_actual < 0 or p_actual >= 'Infinity'::numeric
    or p_input_tokens is null or p_input_tokens < 0 or p_output_tokens is null or p_output_tokens < 0 then
    raise exception 'Invalid AI usage';
  end if;
  select * into r from public.ai_budget_reservations where id=p_id;
  if not found then raise exception 'Unknown AI reservation'; end if;
  perform pg_catalog.pg_advisory_xact_lock(883, r.budget_day - date '2000-01-01');
  select * into r from public.ai_budget_reservations where id=p_id for update;
  if r.state='settled' then
    return r.actual_usd=p_actual and exists(select 1 from public.ai_usage where reservation_id=p_id and cost_usd=round(p_actual,6)
      and input_tokens=p_input_tokens and output_tokens=p_output_tokens);
  end if;
  insert into public.ai_usage(feature,model,input_tokens,output_tokens,cost_usd,profile_id,space_id,created_at,reservation_id)
    values(r.feature,r.model,p_input_tokens,p_output_tokens,p_actual,r.profile_id,r.space_id,r.created_at,p_id);
  update public.ai_budget_reservations set state='settled',actual_usd=p_actual,settled_at=clock_timestamp(),reason=null where id=p_id;
  return true;
end;
$$;
create function public.ai_hold_attempt(p_id uuid, p_reason text)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if p_reason is null or p_reason not in ('provider_failed','stream_failed','settle_failed') then raise exception 'Invalid hold reason'; end if;
  update public.ai_budget_reservations set state='uncertain',reason=p_reason where id=p_id and state <> 'settled';
  return found;
end;
$$;
revoke execute on function public.ai_reserve_attempt(uuid,uuid,text,text,numeric,uuid,uuid,numeric,numeric,numeric) from public,anon,authenticated;
revoke execute on function public.ai_settle_attempt(uuid,integer,integer,numeric) from public,anon,authenticated;
revoke execute on function public.ai_hold_attempt(uuid,text) from public,anon,authenticated;
grant execute on function public.ai_reserve_attempt(uuid,uuid,text,text,numeric,uuid,uuid,numeric,numeric,numeric) to service_role;
grant execute on function public.ai_settle_attempt(uuid,integer,integer,numeric) to service_role;
grant execute on function public.ai_hold_attempt(uuid,text) to service_role;

create function public.ai_budget_status_today()
returns table(feature text, spent numeric, reserved numeric, uncertain numeric, pending_ids text[])
language sql stable security definer set search_path = '' as $$
  with d as (select (now() at time zone 'utc')::date as day), costs as (
    select u.feature, coalesce(r.actual_usd,u.cost_usd) as spent, 0::numeric as reserved, 0::numeric as uncertain, null::text as pending_id
    from public.ai_usage u left join public.ai_budget_reservations r on r.id=u.reservation_id cross join d where u.created_at >= d.day::timestamp at time zone 'utc'
      and u.created_at < (d.day+1)::timestamp at time zone 'utc'
    union all
    select r.feature,0,case when state='reserved' then estimated_usd else 0 end,
      case when state='uncertain' then estimated_usd else 0 end, r.id::text
    from public.ai_budget_reservations r,d where r.budget_day=d.day and r.state <> 'settled'
    union all
    -- Older holds retain visible references; financial admission remains on the originating UTC day.
    select r.feature,0,0,0,r.id::text from public.ai_budget_reservations r,d
      where r.budget_day<>d.day and r.state<>'settled'
  ) select feature,sum(spent),sum(reserved),sum(uncertain),
    (array_agg(pending_id order by pending_id) filter(where pending_id is not null))[1:100]
  from costs group by feature;
$$;
revoke execute on function public.ai_budget_status_today() from public,anon,authenticated;
grant execute on function public.ai_budget_status_today() to service_role;

create function public.ai_member_turns_today(p_profile uuid)
returns bigint language sql stable security definer set search_path = '' as $$
  select count(distinct coalesce(r.operation_id,u.id)) from public.ai_usage u
  left join public.ai_budget_reservations r on r.id=u.reservation_id
  where u.feature='vera-chat' and u.profile_id=p_profile
    and u.created_at >= date_trunc('day',now() at time zone 'utc') at time zone 'utc';
$$;
revoke execute on function public.ai_member_turns_today(uuid) from public,anon,authenticated;
grant execute on function public.ai_member_turns_today(uuid) to service_role;
