-- Generated by CLI as 20261009011913; renumbered to reserved ordered slot080.
-- Free and paid Space replies share the existing conversation store; no receiving/DNS provisioning.
alter table public.comms_conversations add constraint comms_conversations_id_space_unique unique(id,space_id);
create table public.space_email_reply_aliases (
 alias_key text primary key check(alias_key ~ '^[a-f0-9]{20}$'),
 space_id uuid not null references public.spaces(id) on delete cascade,
 conversation_id uuid not null unique,
 conversation_ref text not null check(conversation_ref ~ '^[0-9]+$'),
 local_prefix text not null check(local_prefix ~ '^[a-z0-9-]{1,7}$'),
 receiving_domain text not null check(receiving_domain=lower(receiving_domain) and receiving_domain !~ '[[:space:]@/]'),
 version integer not null default 2 check(version=2),
 revoked_at timestamptz,
 created_at timestamptz not null default now(),
 foreign key(conversation_id,space_id) references public.comms_conversations(id,space_id) on delete cascade
);
create index space_email_reply_aliases_space_idx on public.space_email_reply_aliases(space_id);
alter table public.space_email_reply_aliases enable row level security;
revoke all on public.space_email_reply_aliases from public,anon,authenticated;
grant all on public.space_email_reply_aliases to service_role;
create table public.space_email_reply_quarantine (
 id uuid primary key default gen_random_uuid(),
 reason text not null check(reason in ('ambiguous_alias','malformed_alias','unknown_or_revoked_alias','invalid_alias_proof','tenant_mapping_mismatch')),
 recipient_fingerprint text not null check(recipient_fingerprint ~ '^[a-f0-9]{64}$'),
 message_fingerprint text not null check(message_fingerprint ~ '^[a-f0-9]{64}$'),
 created_at timestamptz not null default now(),
 unique(message_fingerprint,recipient_fingerprint)
);
alter table public.space_email_reply_quarantine enable row level security;
revoke all on public.space_email_reply_quarantine from public,anon,authenticated;
grant all on public.space_email_reply_quarantine to service_role;
