import { beforeEach, describe, expect, it, vi } from 'vitest'
const state=vi.hoisted(()=>({space:{slug:'danieltyack'},conv:{id:'c1',ref:'42',space_id:'s1'},row:null as Record<string,unknown>|null,error:false,quarantine:[] as Record<string,unknown>[]}))
vi.mock('@/lib/supabase/admin',()=>({createAdminClient:()=>({from:(name:string)=>{
 const filters:Record<string,unknown>={};let write:Record<string,unknown>|null=null
 const q={select:()=>q,eq:(k:string,v:unknown)=>{filters[k]=v;return q},insert:(v:Record<string,unknown>)=>{write=v;return q},upsert:(v:Record<string,unknown>)=>{write=v;return q},
 maybeSingle:async()=>{const row=name==='spaces'?{...state.space,id:'s1'}:name==='comms_conversations'?state.conv:state.row;return{data:row&&Object.entries(filters).every(([k,v])=>String(row[k as keyof typeof row])===String(v))?row:null,error:state.error?{}:null}},
 single:async()=>{if(name==='space_email_reply_aliases')state.row=write;if(name==='space_email_reply_quarantine'&&write)state.quarantine.push(write);return{data:write?{...write,id:'saved'}:null,error:state.error?{}:null}}};return q}})}))
import { REPLY_DOMAIN } from './reply-address'
import { buildSpaceConversationReplyAddress, resolveTenantReplyAlias, quarantineTenantReplyAlias } from './tenant-reply-alias'
beforeEach(()=>{vi.stubEnv('CONVERSATION_TOKEN_SECRET','tenant-reply-alias-fixture-secret-32bytes');vi.stubEnv('CONVERSATION_REPLY_DOMAIN','reply.configured.test');vi.stubEnv('RESEND_INBOUND_WEBHOOK_SECRET','fixture-webhook');vi.stubEnv('SPACE_EMAIL_REPLY_ALIASES_ENABLED','true');state.row=null;state.error=false;state.quarantine=[];state.conv={id:'c1',ref:'42',space_id:'s1'}})
describe('tenant-bound Frequency reply aliases',()=>{
 it('issues a compact slug-derived member alias and resolves only its exact tenant conversation',async()=>{const a=await buildSpaceConversationReplyAddress('42','s1');expect(a.split('@')[0].length).toBeLessThanOrEqual(64);expect(a).toMatch(/^danielt\.r2\./);expect(await resolveTenantReplyAlias([a])).toEqual({kind:'ready',spaceId:'s1',conversationId:'c1',ref:'42'});expect(await buildSpaceConversationReplyAddress('42','s1')).toBe(a)})
 it('preserves legacy issuance by default and requires explicit receiving configuration to enable',async()=>{vi.stubEnv('SPACE_EMAIL_REPLY_ALIASES_ENABLED','false');expect(await buildSpaceConversationReplyAddress('42','s1')).toContain('reply+42-');vi.stubEnv('SPACE_EMAIL_REPLY_ALIASES_ENABLED','true');vi.stubEnv('CONVERSATION_REPLY_DOMAIN','');await expect(buildSpaceConversationReplyAddress('42','s1')).rejects.toThrow('explicitly configured');expect(state.row).toBeNull()})
 it('rejects Space/ref substitution before issuing a route',async()=>{await expect(buildSpaceConversationReplyAddress('42','s2')).rejects.toThrow('unavailable');expect(state.row).toBeNull()})
 it('quarantines wrong domain, forged proof, mutable tenant mapping and revoked aliases',async()=>{const a=await buildSpaceConversationReplyAddress('42','s1');expect(await resolveTenantReplyAlias([a.replace('@reply.configured.test','@evil.test')])).toMatchObject({kind:'quarantine',reason:'invalid_alias_proof'});expect(await resolveTenantReplyAlias([a.replace(/\.[a-f0-9]{32}@/,`.${'0'.repeat(32)}@`)])).toMatchObject({kind:'quarantine'});state.conv.space_id='s2';expect(await resolveTenantReplyAlias([a])).toMatchObject({kind:'quarantine',reason:'tenant_mapping_mismatch'});state.conv.space_id='s1';state.row!.revoked_at='now';expect(await resolveTenantReplyAlias([a])).toMatchObject({kind:'quarantine',reason:'unknown_or_revoked_alias'});await expect(buildSpaceConversationReplyAddress('42','s1')).rejects.toThrow('revoked')})
 it('does not downgrade malformed or multiple aliases to contact matching; legacy addresses remain legacy',async()=>{expect(await resolveTenantReplyAlias(['bad.r2.tag@reply.configured.test'])).toMatchObject({kind:'quarantine'});const a=await buildSpaceConversationReplyAddress('42','s1');expect(await resolveTenantReplyAlias([a,a])).toMatchObject({kind:'quarantine',reason:'ambiguous_alias'});expect(await resolveTenantReplyAlias([a,`reply+42-${'a'.repeat(32)}@${REPLY_DOMAIN}`])).toMatchObject({kind:'quarantine',reason:'ambiguous_alias'});expect(await resolveTenantReplyAlias(['reply+42-old@reply.configured.test'])).toEqual({kind:'none'})})
 it('continues honoring issued aliases when issuance is disabled or configured domain changes',async()=>{const a=await buildSpaceConversationReplyAddress('42','s1');vi.stubEnv('SPACE_EMAIL_REPLY_ALIASES_ENABLED','false');vi.stubEnv('CONVERSATION_REPLY_DOMAIN','reply.new.test');expect(await resolveTenantReplyAlias([a])).toMatchObject({kind:'ready'})})
 it('fails on lookup/quarantine faults, retaining no raw sender, recipient or body',async()=>{await quarantineTenantReplyAlias('malformed_alias',['bad.r2.tag@reply.configured.test'],'<private-message>');expect(JSON.stringify(state.quarantine)).not.toContain('private-message');expect(JSON.stringify(state.quarantine)).not.toContain('configured.test');state.error=true;await expect(resolveTenantReplyAlias(['danielt.r2.'+'a'.repeat(20)+'.'+'b'.repeat(32)+'@reply.configured.test'])).rejects.toThrow('lookup');await expect(quarantineTenantReplyAlias('malformed_alias',[],'m')).rejects.toThrow('quarantine')})
})
